#!/bin/bash
for i in `seq 1 10000`;
do
#         curl -H "Content-Type: application/json" -d "{\"firstName\":\""$i"\", \"lastName\":\"flood!\"}" -X POST http://localhost/api/profiles/public
         curl -H "Content-Type: application/json" -X GET http://192.168.0.197/api/
         echo $i
done  